[package]
name = "hdars"
version = "0.1.0"
authors = ["Jeremy Cline <jcline@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix="0.16.1"
gtk="0.8.1"
glib="0.9.3"
